sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.npm
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
node_js:
  - '8'
before_install:
  - npm i -g npm@latest
env:
  - SKIP_TRAVIS_WAIT=true
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - master
