sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
addons:
  apt:
    packages:
      - xvfb
node_js:
  - '5'
before_install:
  - npm i -g npm@latest
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm upgrade && npm prune && npm rebuild
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - master
